export const GET_ISSUES = 'GET_ISSUES';
export const GET_ISSUES_ERROR = 'GET_ISSUES_ERROR';
export const GET_ISSUES_RECEIVED = 'GET_ISSUES_RECEIVED';
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
export const GET_COMMENTS_RECEIVED = 'GET_COMMENTS_RECEIVED';
